# Generated by Django 5.2.17 on 2026-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booking_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='booking',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='booking',
            name='moderation_reason',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='visits_limit',
            field=models.PositiveIntegerField(help_text='0 = безлимит', verbose_name='Лимит посещений'),
        ),
    ]
