# Generated by Django 5.2.17 on 2026-09-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_booking_deleted_at_booking_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
